### ISSUE TITLE
profile data needed in snmp data in Splunk: please add cycle time and profile name

### ISSUE THREAD

**Issue by hhgsplk** [splunk/splunk-connect-for-snmp-poller#85]
When you want to calculate the interface utilization with inOctets and outOctets, you need the polling cycle time in the snmp metrics data in Splunk. Please add the cycle time and the profile name to the polling data. 
See the description and formula here on this Cisco page:
https://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/8141-calculate-bandwidth-snmp.html

**Comment by hhgsplk** [comment]
this is an example:
```
| mstats rate_avg("sc4snmp.IF-MIB.ifHCInOctets_6") AS inn rate_avg("sc4snmp.IF-MIB.ifHCOutOctets_6") AS outt latest("sc4snmp.IF-MIB.ifHighSpeed_6") AS ifHighSpeed_6 chart=true WHERE "index"="em_metrics" host="myswitch" span=60s chart.useother=false chart.agg=max chart.limit=top50 
| eval throughput=(((inn+outt) * 8 )/(**60***ifHighSpeed_6)) 
| fields - inn, outt,ifHighSpeed_6
```

the **60** is the interval that I hard-coded into the SPL. But I need this as an accessible variable.

**Comment by okuzhel** [comment]
Hi @hhgsplk, 
just letting you know that changes that you have requested was merged into the develop and will be available in the next official release. 

frequency will be added to all metric data, profile name only if it will be defined in the config. 

As an example, `| msearch index="metrics_index`
With changes on develop returns 
`{"index":"metrics_index","freqinseconds":"10","host.name":"10.202.38.128","profile":"basev1l2","metric_name:sc4snmp.IF-MIB.ifHCInOctets_1":17783923} `

So both **profile** and **freqinseconds** are available
